name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build Image
        run: |
          docker build -t  my-python-app .
    
      - uses: Azure/docker-login@v1
        with:
          login-server: hellolabo.azurecr.io
          username: ${{ secrets.LABO_USER }}
          password: ${{ secrets.LABO_PASS }}

      - run: docker tag my-python-app hellolabo.azurecr.io/my-python-app
      - run: docker push hellolabo.azurecr.io/my-python-app
