name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build Image
        run: |
          docker build -t  my-python-app .
      - uses: Azure/container-scan@v0
      
        with:
          image-name: my-python-app
    
      - uses: Azure/docker-login@v1
        with:
          login-server: contoso.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - run: docker push contoso.azurecr.io/k8sdemo:${{ github.sha }}
